/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.azkoyen;

public class AzkoyenControlClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AzkoyenControlClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AzkoyenControlClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AzkoyenControlClass obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AzkoyenControlJNI.delete_AzkoyenControlClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPortO(int value) {
    AzkoyenControlJNI.AzkoyenControlClass_PortO_set(swigCPtr, this, value);
  }

  public int getPortO() {
    return AzkoyenControlJNI.AzkoyenControlClass_PortO_get(swigCPtr, this);
  }

  public void setWarnToCritical(int value) {
    AzkoyenControlJNI.AzkoyenControlClass_WarnToCritical_set(swigCPtr, this, value);
  }

  public int getWarnToCritical() {
    return AzkoyenControlJNI.AzkoyenControlClass_WarnToCritical_get(swigCPtr, this);
  }

  public void setMaxCritical(int value) {
    AzkoyenControlJNI.AzkoyenControlClass_MaxCritical_set(swigCPtr, this, value);
  }

  public int getMaxCritical() {
    return AzkoyenControlJNI.AzkoyenControlClass_MaxCritical_get(swigCPtr, this);
  }

  public void setPath(String value) {
    AzkoyenControlJNI.AzkoyenControlClass_Path_set(swigCPtr, this, value);
  }

  public String getPath() {
    return AzkoyenControlJNI.AzkoyenControlClass_Path_get(swigCPtr, this);
  }

  public void setLogLvl(int value) {
    AzkoyenControlJNI.AzkoyenControlClass_LogLvl_set(swigCPtr, this, value);
  }

  public int getLogLvl() {
    return AzkoyenControlJNI.AzkoyenControlClass_LogLvl_get(swigCPtr, this);
  }

  public void setMaximumPorts(int value) {
    AzkoyenControlJNI.AzkoyenControlClass_MaximumPorts_set(swigCPtr, this, value);
  }

  public int getMaximumPorts() {
    return AzkoyenControlJNI.AzkoyenControlClass_MaximumPorts_get(swigCPtr, this);
  }

  public void setGlobals(GlobalVariables value) {
    AzkoyenControlJNI.AzkoyenControlClass_Globals_set(swigCPtr, this, GlobalVariables.getCPtr(value), value);
  }

  public GlobalVariables getGlobals() {
    long cPtr = AzkoyenControlJNI.AzkoyenControlClass_Globals_get(swigCPtr, this);
    return (cPtr == 0) ? null : new GlobalVariables(cPtr, false);
  }

  public AzkoyenControlClass() {
    this(AzkoyenControlJNI.new_AzkoyenControlClass(), true);
  }

  public void InitLog() {
    AzkoyenControlJNI.AzkoyenControlClass_InitLog(swigCPtr, this);
  }

  public Response_t Connect() {
    return new Response_t(AzkoyenControlJNI.AzkoyenControlClass_Connect(swigCPtr, this), true);
  }

  public Response_t CheckDevice() {
    return new Response_t(AzkoyenControlJNI.AzkoyenControlClass_CheckDevice(swigCPtr, this), true);
  }

  public Response_t StartReader() {
    return new Response_t(AzkoyenControlJNI.AzkoyenControlClass_StartReader(swigCPtr, this), true);
  }

  public CoinError_t GetCoin() {
    return new CoinError_t(AzkoyenControlJNI.AzkoyenControlClass_GetCoin(swigCPtr, this), true);
  }

  public CoinLost_t GetLostCoins() {
    return new CoinLost_t(AzkoyenControlJNI.AzkoyenControlClass_GetLostCoins(swigCPtr, this), true);
  }

  public Response_t ModifyChannels(int InhibitMask1, int InhibitMask2) {
    return new Response_t(AzkoyenControlJNI.AzkoyenControlClass_ModifyChannels(swigCPtr, this, InhibitMask1, InhibitMask2), true);
  }

  public Response_t StopReader() {
    return new Response_t(AzkoyenControlJNI.AzkoyenControlClass_StopReader(swigCPtr, this), true);
  }

  public Response_t ResetDevice() {
    return new Response_t(AzkoyenControlJNI.AzkoyenControlClass_ResetDevice(swigCPtr, this), true);
  }

  public TestStatus_t TestStatus() {
    return new TestStatus_t(AzkoyenControlJNI.AzkoyenControlClass_TestStatus(swigCPtr, this), true);
  }

  public Response_t CheckCodes(int Check) {
    return new Response_t(AzkoyenControlJNI.AzkoyenControlClass_CheckCodes(swigCPtr, this, Check), true);
  }

}
