/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package hardware.azkoyen;

public class GlobalVariables {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GlobalVariables(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GlobalVariables obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(GlobalVariables obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AzkoyenControlJNI.delete_GlobalVariables(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAzkoyenObject(AzkoyenClass value) {
    AzkoyenControlJNI.GlobalVariables_AzkoyenObject_set(swigCPtr, this, AzkoyenClass.getCPtr(value), value);
  }

  public AzkoyenClass getAzkoyenObject() {
    long cPtr = AzkoyenControlJNI.GlobalVariables_AzkoyenObject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AzkoyenClass(cPtr, false);
  }

  public void setAzkoyenPointer(AzkoyenClass value) {
    AzkoyenControlJNI.GlobalVariables_AzkoyenPointer_set(swigCPtr, this, AzkoyenClass.getCPtr(value), value);
  }

  public AzkoyenClass getAzkoyenPointer() {
    long cPtr = AzkoyenControlJNI.GlobalVariables_AzkoyenPointer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new AzkoyenClass(cPtr, false);
  }

  public void setSMObject(SMClass value) {
    AzkoyenControlJNI.GlobalVariables_SMObject_set(swigCPtr, this, SMClass.getCPtr(value), value);
  }

  public SMClass getSMObject() {
    long cPtr = AzkoyenControlJNI.GlobalVariables_SMObject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SMClass(cPtr, false);
  }

  public GlobalVariables() {
    this(AzkoyenControlJNI.new_GlobalVariables(), true);
  }

}
